"""pyclickplc - Utilities for AutomationDirect CLICK PLCs."""

from .addresses import (
    AddressRecord,
    format_address_display,
    get_addr_key,
    normalize_address,
    parse_addr_key,
    parse_address,
    parse_address_display,
)
from .banks import (
    BANKS,
    BIT_ONLY_TYPES,
    DATA_TYPE_DISPLAY,
    DATA_TYPE_HINTS,
    DEFAULT_RETENTIVE,
    INTERLEAVED_PAIRS,
    INTERLEAVED_TYPE_PAIRS,
    MEMORY_TYPE_BASES,
    MEMORY_TYPE_TO_DATA_TYPE,
    NON_EDITABLE_TYPES,
    PAIRED_RETENTIVE_TYPES,
    BankConfig,
    DataType,
    is_valid_address,
)
from .validation import (
    COMMENT_MAX_LENGTH,
    FLOAT_MAX,
    FLOAT_MIN,
    FORBIDDEN_CHARS,
    INT2_MAX,
    INT2_MIN,
    INT_MAX,
    INT_MIN,
    NICKNAME_MAX_LENGTH,
    RESERVED_NICKNAMES,
    validate_comment,
    validate_initial_value,
    validate_nickname,
)

__all__ = [
    # banks
    "BankConfig",
    "BANKS",
    "DataType",
    "DATA_TYPE_DISPLAY",
    "DATA_TYPE_HINTS",
    "DEFAULT_RETENTIVE",
    "INTERLEAVED_PAIRS",
    "INTERLEAVED_TYPE_PAIRS",
    "MEMORY_TYPE_BASES",
    "MEMORY_TYPE_TO_DATA_TYPE",
    "NON_EDITABLE_TYPES",
    "PAIRED_RETENTIVE_TYPES",
    "BIT_ONLY_TYPES",
    "is_valid_address",
    # addresses
    "AddressRecord",
    "get_addr_key",
    "parse_addr_key",
    "format_address_display",
    "parse_address_display",
    "parse_address",
    "normalize_address",
    # validation
    "NICKNAME_MAX_LENGTH",
    "COMMENT_MAX_LENGTH",
    "FORBIDDEN_CHARS",
    "RESERVED_NICKNAMES",
    "INT_MIN",
    "INT_MAX",
    "INT2_MIN",
    "INT2_MAX",
    "FLOAT_MIN",
    "FLOAT_MAX",
    "validate_nickname",
    "validate_comment",
    "validate_initial_value",
]
