"""pyclickplc - Utilities for AutomationDirect CLICK PLCs."""

from .addresses import (
    AddressRecord,
    format_address_display,
    get_addr_key,
    normalize_address,
    parse_addr_key,
    parse_address,
    parse_address_display,
)
from .banks import (
    BANKS,
    BIT_ONLY_TYPES,
    DATA_TYPE_DISPLAY,
    DATA_TYPE_HINTS,
    DEFAULT_RETENTIVE,
    INTERLEAVED_PAIRS,
    INTERLEAVED_TYPE_PAIRS,
    MEMORY_TYPE_BASES,
    MEMORY_TYPE_TO_DATA_TYPE,
    NON_EDITABLE_TYPES,
    PAIRED_RETENTIVE_TYPES,
    BankConfig,
    DataType,
    is_valid_address,
)
from .blocks import (
    BlockRange,
    BlockTag,
    HasComment,
    compute_all_block_ranges,
    extract_block_name,
    find_block_range_indices,
    find_paired_tag_index,
    format_block_tag,
    get_all_block_names,
    get_block_type,
    is_block_name_available,
    is_block_tag,
    parse_block_tag,
    strip_block_tag,
    validate_block_span,
)
from .dataview import (
    MAX_DATAVIEW_ROWS,
    MEMORY_TYPE_TO_CODE,
    WRITABLE_SC,
    WRITABLE_SD,
    DataviewRow,
    TypeCode,
    create_empty_dataview,
    display_to_storage,
    export_cdv,
    get_dataview_folder,
    get_type_code_for_address,
    is_address_writable,
    list_cdv_files,
    load_cdv,
    save_cdv,
    storage_to_display,
)
from .modbus import (
    MODBUS_MAPPINGS,
    MODBUS_SIGNED,
    MODBUS_WIDTH,
    STRUCT_FORMATS,
    ModbusMapping,
    modbus_to_plc,
    pack_value,
    plc_to_modbus,
    unpack_value,
)
from .nicknames import (
    CSV_COLUMNS,
    DATA_TYPE_CODE_TO_STR,
    DATA_TYPE_STR_TO_CODE,
    read_csv,
    read_mdb_csv,
    write_csv,
)
from .validation import (
    COMMENT_MAX_LENGTH,
    FLOAT_MAX,
    FLOAT_MIN,
    FORBIDDEN_CHARS,
    INT2_MAX,
    INT2_MIN,
    INT_MAX,
    INT_MIN,
    NICKNAME_MAX_LENGTH,
    RESERVED_NICKNAMES,
    validate_comment,
    validate_initial_value,
    validate_nickname,
)

__all__ = [
    # banks
    "BankConfig",
    "BANKS",
    "DataType",
    "DATA_TYPE_DISPLAY",
    "DATA_TYPE_HINTS",
    "DEFAULT_RETENTIVE",
    "INTERLEAVED_PAIRS",
    "INTERLEAVED_TYPE_PAIRS",
    "MEMORY_TYPE_BASES",
    "MEMORY_TYPE_TO_DATA_TYPE",
    "NON_EDITABLE_TYPES",
    "PAIRED_RETENTIVE_TYPES",
    "BIT_ONLY_TYPES",
    "is_valid_address",
    # addresses
    "AddressRecord",
    "get_addr_key",
    "parse_addr_key",
    "format_address_display",
    "parse_address_display",
    "parse_address",
    "normalize_address",
    # blocks
    "BlockTag",
    "BlockRange",
    "HasComment",
    "parse_block_tag",
    "get_block_type",
    "is_block_tag",
    "extract_block_name",
    "strip_block_tag",
    "format_block_tag",
    "get_all_block_names",
    "is_block_name_available",
    "find_paired_tag_index",
    "find_block_range_indices",
    "compute_all_block_ranges",
    "validate_block_span",
    # modbus
    "ModbusMapping",
    "MODBUS_MAPPINGS",
    "MODBUS_WIDTH",
    "MODBUS_SIGNED",
    "STRUCT_FORMATS",
    "plc_to_modbus",
    "modbus_to_plc",
    "pack_value",
    "unpack_value",
    # dataview
    "TypeCode",
    "DataviewRow",
    "MEMORY_TYPE_TO_CODE",
    "WRITABLE_SC",
    "WRITABLE_SD",
    "MAX_DATAVIEW_ROWS",
    "get_type_code_for_address",
    "is_address_writable",
    "create_empty_dataview",
    "storage_to_display",
    "display_to_storage",
    "export_cdv",
    "load_cdv",
    "save_cdv",
    "get_dataview_folder",
    "list_cdv_files",
    # nicknames
    "CSV_COLUMNS",
    "DATA_TYPE_STR_TO_CODE",
    "DATA_TYPE_CODE_TO_STR",
    "read_csv",
    "write_csv",
    "read_mdb_csv",
    # validation
    "NICKNAME_MAX_LENGTH",
    "COMMENT_MAX_LENGTH",
    "FORBIDDEN_CHARS",
    "RESERVED_NICKNAMES",
    "INT_MIN",
    "INT_MAX",
    "INT2_MIN",
    "INT2_MAX",
    "FLOAT_MIN",
    "FLOAT_MAX",
    "validate_nickname",
    "validate_comment",
    "validate_initial_value",
]
